version: "2"
​
networks:
  custom:
    driver: bridge
​
services:
​
  proxy:
    image: hrak/nginx-ldap:1.16.1
    container_name: proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/html:/usr/local/nginx/html:ro
    networks:
      - custom
    ports:
      - "8080:8080"
    links:
      - grafana
​
  openldap:
    container_name: openldap
    build: ./openldap
    networks:
      - custom
    environment:
      - LDAP_ORGANISATION=MVP
      - LDAP_DOMAIN=mvp.org
      - LDAP_ADMIN_PASSWORD=admin
  
  jenkins:
    build:
      context: ./jenkins_master
      args:
        HOST_UID: 1001
        HOST_GID: 998
    container_name: jenkins
    networks:
      - custom
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/www/jenkins:/var/jenkins_home
​
  jenkins_slave:
    build: jenkins_slave/
    container_name: jenkins_slave
    networks:
      - custom
    depends_on:
      - jenkins
    environment:
      - "SWARM_MASTER=http://jenkins:8080/jenkins/"
      - "SLAVE_EXECUTORS=2"
      - "SLAVE_DESCRIPTION=test"
      - "SWARM_USER=test"
      - "SWARM_PASSWORD=t3st"
      - "SLAVE_NAME=test"
      - "SLAVE_LABELS=test"
      - "SLAVE_MODE=exclusive"
  
  gogs:
    image: gogs/gogs:0.11.4
    container_name: gogs
    networks:
      - custom
    expose:
      - "3000"
    volumes:
      - "./gogs/conf:/data/gogs/conf"
​
  prometheus:
    image: prom/prometheus:v1.5.2
    container_name: prometheus
    networks:
      - custom
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "-web.external-url=http://127.0.0.1:8080/prometheus"
      - "-config.file=/etc/prometheus/prometheus.yml"
​
  node_exporter:
    image: prom/node-exporter:v1.1.1
    container_name: node_exporter
    networks:
      - custom
​
  grafana:
    image: grafana/grafana:4.3.2
    container_name: grafana
    networks:
      - custom
    environment:
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://127.0.0.1:8080/grafana
    depends_on:
      - prometheus
    expose:
