pipline {

   agent any 
   
   stages {
   
     stage("build) {
     
       steps {
          
       }
     }
     stages("test") {
      
       steps {
          
       }
       
    }
    
    stages("deploy") {
      
       steps {
       
        }
     }
   }
}
